In [8]:

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Airbnb_Data.csv')

display(df.head())

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,...,40.696524,-73.991617,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,https://a0.muscache.com/im/pictures/6d7cbbf7-c...,11201,1.0,1.0
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,...,40.766115,-73.989040,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.0,https://a0.muscache.com/im/pictures/348a55fe-4...,10019,3.0,3.0
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,...,40.808110,-73.943756,The Garden Oasis,Harlem,10,92.0,https://a0.muscache.com/im/pictures/6fae5362-9...,10027,1.0,3.0
3,13418779,6.620073,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,flexible,True,...,37.772004,-122.431619,Beautiful Flat in the Heart of SF!,Lower Haight,0,NaN,https://a0.muscache.com/im/pictures/72208dad-9...,94117.0,2.0,2.0
4,3808709,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,...,38.925627,-77.034596,Great studio in midtown DC,Columbia Heights,4,40.0,NaN,20009,0.0,1.0

In [9]:

print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

print("\nDataset information:")
df.info()

Dataset shape: (74111, 29)

Column names:
['id', 'log_price', 'property_type', 'room_type', 'amenities', 'accommodates', 'bathrooms', 'bed_type', 'cancellation_policy', 'cleaning_fee', 'city', 'description', 'first_review', 'host_has_profile_pic', 'host_identity_verified', 'host_response_rate', 'host_since', 'instant_bookable', 'last_review', 'latitude', 'longitude', 'name', 'neighbourhood', 'number_of_reviews', 'review_scores_rating', 'thumbnail_url', 'zipcode', 'bedrooms', 'beds']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74111 entries, 0 to 74110
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      74111 non-null  int64
 1   log_price               74111 non-null  float64
 2   property_type           74111 non-null  object
 3   room_type               74111 non-null  object
 4   amenities               74111 non-null  object
 5   accommodates            74111 non-null  int64
 6   bathrooms               73911 non-null  float64
 7   bed_type                74111 non-null  object
 8   cancellation_policy     74111 non-null  object
 9   cleaning_fee            74111 non-null  bool
 10  city                    74111 non-null  object
 11  description             74111 non-null  object
 12  first_review            58247 non-null  object
 13  host_has_profile_pic    73923 non-null  object
 14  host_identity_verified  73923 non-null  object
 15  host_response_rate      55812 non-null  object
 16  host_since              73923 non-null  object
 17  instant_bookable        74111 non-null  object
 18  last_review             58284 non-null  object
 19  latitude                74111 non-null  float64
 20  longitude               74111 non-null  float64
 21  name                    74111 non-null  object
 22  neighbourhood           67239 non-null  object
 23  number_of_reviews       74111 non-null  int64
 24  review_scores_rating    57389 non-null  float64
 25  thumbnail_url           65895 non-null  object
 26  zipcode                 73145 non-null  object
 27  bedrooms                74020 non-null  float64
 28  beds                    73980 non-null  float64
dtypes: bool(1), float64(7), int64(3), object(18)
memory usage: 15.9+ MB

In [10]:

print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types and non-missing values:")
df.info()

print("\nFirst five rows:")
display(df.head())

Dataset shape: (74111, 29)

Column names:
['id', 'log_price', 'property_type', 'room_type', 'amenities', 'accommodates', 'bathrooms', 'bed_type', 'cancellation_policy', 'cleaning_fee', 'city', 'description', 'first_review', 'host_has_profile_pic', 'host_identity_verified', 'host_response_rate', 'host_since', 'instant_bookable', 'last_review', 'latitude', 'longitude', 'name', 'neighbourhood', 'number_of_reviews', 'review_scores_rating', 'thumbnail_url', 'zipcode', 'bedrooms', 'beds']

Data types and non-missing values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74111 entries, 0 to 74110
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      74111 non-null  int64
 1   log_price               74111 non-null  float64
 2   property_type           74111 non-null  object
 3   room_type               74111 non-null  object
 4   amenities               74111 non-null  object
 5   accommodates            74111 non-null  int64
 6   bathrooms               73911 non-null  float64
 7   bed_type                74111 non-null  object
 8   cancellation_policy     74111 non-null  object
 9   cleaning_fee            74111 non-null  bool
 10  city                    74111 non-null  object
 11  description             74111 non-null  object
 12  first_review            58247 non-null  object
 13  host_has_profile_pic    73923 non-null  object
 14  host_identity_verified  73923 non-null  object
 15  host_response_rate      55812 non-null  object
 16  host_since              73923 non-null  object
 17  instant_bookable        74111 non-null  object
 18  last_review             58284 non-null  object
 19  latitude                74111 non-null  float64
 20  longitude               74111 non-null  float64
 21  name                    74111 non-null  object
 22  neighbourhood           67239 non-null  object
 23  number_of_reviews       74111 non-null  int64
 24  review_scores_rating    57389 non-null  float64
 25  thumbnail_url           65895 non-null  object
 26  zipcode                 73145 non-null  object
 27  bedrooms                74020 non-null  float64
 28  beds                    73980 non-null  float64
dtypes: bool(1), float64(7), int64(3), object(18)
memory usage: 15.9+ MB

First five rows:

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,...,40.696524,-73.991617,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,https://a0.muscache.com/im/pictures/6d7cbbf7-c...,11201,1.0,1.0
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,...,40.766115,-73.989040,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.0,https://a0.muscache.com/im/pictures/348a55fe-4...,10019,3.0,3.0
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,...,40.808110,-73.943756,The Garden Oasis,Harlem,10,92.0,https://a0.muscache.com/im/pictures/6fae5362-9...,10027,1.0,3.0
3,13418779,6.620073,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,flexible,True,...,37.772004,-122.431619,Beautiful Flat in the Heart of SF!,Lower Haight,0,NaN,https://a0.muscache.com/im/pictures/72208dad-9...,94117.0,2.0,2.0
4,3808709,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,...,38.925627,-77.034596,Great studio in midtown DC,Columbia Heights,4,40.0,NaN,20009,0.0,1.0

In [14]:

# Create a safe working copy
df_raw = df.copy()
df_clean = df.copy()

print("Original dataset:", df_raw.shape)
print("Working copy:", df_clean.shape)

Original dataset: (74111, 29)
Working copy: (74111, 29)

In [15]:

# Check missing values in the working copy

missing_data = pd.DataFrame({
    "Missing Count": df_clean.isnull().sum(),
    "Missing Percentage": (df_clean.isnull().mean() * 100).round(2)
})

missing_data = missing_data[missing_data["Missing Count"] > 0]
missing_data = missing_data.sort_values(
    by="Missing Count", ascending=False
)

display(missing_data)

                        Missing Count  Missing Percentage
host_response_rate              18299               24.69
review_scores_rating            16722               22.56
first_review                    15864               21.41
last_review                     15827               21.36
thumbnail_url                    8216               11.09
neighbourhood                    6872                9.27
zipcode                           966                1.30
bathrooms                         200                0.27
host_has_profile_pic              188                0.25
host_identity_verified            188                0.25
host_since                        188                0.25
beds                              131                0.18
bedrooms                           91                0.12

In [16]:

# A. Fill missing numerical values with the median
# These columns have relatively few missing values.

for col in ["bathrooms", "bedrooms", "beds"]:
    median_value = df_clean[col].median()
    df_clean[col] = df_clean[col].fillna(median_value)

# B. Mark missing categorical information as Unknown
for col in ["neighbourhood", "zipcode",
            "host_has_profile_pic", "host_identity_verified"]:
    df_clean[col] = df_clean[col].fillna("Unknown")

print("Missing values handled for selected columns.")

Missing values handled for selected columns.

In [19]:

remaining = df_clean.isnull().sum()
display(remaining[remaining > 0].to_frame("Remaining Missing Values"))

                      Remaining Missing Values
first_review                             15864
host_response_rate                       18299
host_since                                 188
last_review                              15827
review_scores_rating                     16722
thumbnail_url                             8216

### Handling Missing Values

Missing values were identified using `isnull().sum()` and their percentages were calculated. The missing values in `bathrooms`, `bedrooms`, and `beds` were filled using their median values because these numerical columns had relatively few missing records. Missing values in `neighbourhood`, `zipcode`, `host_has_profile_pic`, and `host_identity_verified` were replaced with `Unknown` to preserve the fact that the information was unavailable.

Missing review dates, review ratings, host response rates, and thumbnail URLs were retained for further inspection because their absence may have a meaningful explanation. The original dataset was preserved in `df_raw`, while cleaning was performed on `df_clean`.

In [20]:

# Check complete duplicate rows
duplicate_rows = df_clean.duplicated().sum()

# Check duplicate listing IDs
duplicate_ids = df_clean["id"].duplicated().sum()

print("Complete duplicate rows:", duplicate_rows)
print("Duplicate listing IDs:", duplicate_ids)

Complete duplicate rows: 0
Duplicate listing IDs: 0

### Duplicate Record Detection

The dataset was checked for complete duplicate rows using `df_clean.duplicated()` and for repeated listing IDs using `df_clean["id"].duplicated()`. Both checks returned zero duplicates. Therefore, no records were removed because there were no duplicate rows or repeated listing IDs.

In [21]:

categorical_cols = [
    "property_type",
    "room_type",
    "bed_type",
    "cancellation_policy",
    "city",
    "host_has_profile_pic",
    "host_identity_verified",
    "instant_bookable"
]

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df_clean[col].value_counts(dropna=False))

--- property_type ---
property_type
Apartment             49003
House                 16511
Condominium            2658
Townhouse              1692
Loft                   1244
Other                   607
Guesthouse              498
Bed & Breakfast         462
Bungalow                366
Villa                   179
Dorm                    142
Guest suite             123
Camper/RV                94
Timeshare                77
Cabin                    72
In-law                   71
Hostel                   70
Boutique hotel           69
Boat                     65
Serviced apartment       21
Tent                     18
Castle                   13
Vacation home            11
Yurt                      9
Hut                       8
Treehouse                 7
Chalet                    6
Earth House               4
Tipi                      3
Cave                      2
Train                     2
Casa particular           1
Parking Space             1
Lighthouse                1
Island                    1
Name: count, dtype: int64

--- room_type ---
room_type
Entire home/apt    41310
Private room       30638
Shared room         2163
Name: count, dtype: int64

--- bed_type ---
bed_type
Real Bed         72028
Futon              753
Pull-out Sofa      585
Airbed             477
Couch              268
Name: count, dtype: int64

--- cancellation_policy ---
cancellation_policy
strict             32374
flexible           22545
moderate           19063
super_strict_30      112
super_strict_60       17
Name: count, dtype: int64

--- city ---
city
NYC        32349
LA         22453
SF          6434
DC          5688
Chicago     3719
Boston      3468
Name: count, dtype: int64

--- host_has_profile_pic ---
host_has_profile_pic
t          73697
f            226
Unknown      188
Name: count, dtype: int64

--- host_identity_verified ---
host_identity_verified
t          49748
f          24175
Unknown      188
Name: count, dtype: int64

--- instant_bookable ---
instant_bookable
f    54660
t    19451
Name: count, dtype: int64

In [22]:

# Standardize text values by removing extra spaces
for col in df_clean.select_dtypes(include="object").columns:
    df_clean[col] = df_clean[col].str.strip()

# Make host information easier to understand
binary_text_cols = [
    "host_has_profile_pic",
    "host_identity_verified"
]

for col in binary_text_cols:
    df_clean[col] = df_clean[col].replace({
        "t": "True",
        "f": "False"
    })

# Convert instant_bookable to Boolean values
df_clean["instant_bookable"] = df_clean["instant_bookable"].map({
    "t": True,
    "f": False
})

# Verify the changes
for col in [
    "host_has_profile_pic",
    "host_identity_verified",
    "instant_bookable"
]:
    print(f"\n{col}:")
    print(df_clean[col].value_counts(dropna=False))

host_has_profile_pic:
host_has_profile_pic
True       73697
False        226
Unknown      188
Name: count, dtype: int64

host_identity_verified:
host_identity_verified
True       49748
False      24175
Unknown      188
Name: count, dtype: int64

instant_bookable:
instant_bookable
False    54660
True     19451
Name: count, dtype: int64

In [23]:
# Convert date columns into datetime format
date_cols = ["first_review", "host_since", "last_review"]

for col in date_cols:
    df_clean[col] = pd.to_datetime(df_clean[col], errors="coerce")

# Check the results
df_clean[date_cols].dtypes

first_review    datetime64[ns]
host_since      datetime64[ns]
last_review     datetime64[ns]
dtype: object

In [24]:
df_clean.dtypes

id                                 int64
log_price                        float64
property_type                     object
room_type                         object
amenities                         object
accommodates                       int64
bathrooms                        float64
bed_type                          object
cancellation_policy               object
cleaning_fee                        bool
city                              object
description                       object
first_review              datetime64[ns]
host_has_profile_pic              object
host_identity_verified            object
host_response_rate                object
host_since                datetime64[ns]
instant_bookable                    bool
last_review               datetime64[ns]
latitude                         float64
longitude                        float64
name                              object
neighbourhood                     object
number_of_reviews                  int64
review_scores_rating             float64
thumbnail_url                     object
zipcode                           object
bedrooms                         float64
beds                             float64
dtype: object

In [25]:
# Count missing values in each column
missing = df_clean.isnull().sum()

# Show only columns that still have missing values
missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

host_response_rate      18299
review_scores_rating    16722
first_review            15864
last_review             15827
thumbnail_url            8216
host_since                188
dtype: int64

In [26]:
# Keep missing review dates and ratings as they are.
# They may indicate that a listing has no reviews or rating.

# Replace missing text information with "Unknown"
df_clean["host_response_rate"] = (
    df_clean["host_response_rate"].fillna("Unknown")
)

df_clean["thumbnail_url"] = (
    df_clean["thumbnail_url"].fillna("Unknown")
)

# Keep host_since as a datetime column.
# Missing dates remain NaT because the actual dates are unknown.

# Check remaining missing values
print(df_clean.isnull().sum()[df_clean.isnull().sum() > 0])

first_review            15864
host_since                188
last_review             15827
review_scores_rating    16722
dtype: int64

In [27]:
# Select numerical columns
numeric_cols = [
    "log_price",
    "accommodates",
    "bathrooms",
    "bedrooms",
    "beds",
    "number_of_reviews",
    "review_scores_rating",
    "latitude",
    "longitude"
]

# Display summary statistics
df_clean[numeric_cols].describe().round(2)

,log_price,accommodates,bathrooms,bedrooms,beds,number_of_reviews,review_scores_rating,latitude,longitude
count,74111.00,74111.00,74111.00,74111.00,74111.00,74111.00,57389.00,74111.00,74111.00
mean,4.78,3.16,1.23,1.27,1.71,20.90,94.07,38.45,-92.40
std,0.72,2.15,0.58,0.85,1.25,37.83,7.84,3.08,21.71
min,0.00,1.00,0.00,0.00,0.00,0.00,20.00,33.34,-122.51
25%,4.32,2.00,1.00,1.00,1.00,1.00,92.00,34.13,-118.34
50%,4.71,2.00,1.00,1.00,1.00,6.00,96.00,40.66,-77.00
75%,5.22,4.00,1.00,1.00,2.00,23.00,100.00,40.75,-73.95
max,7.60,16.00,8.00,10.00,18.00,605.00,100.00,42.39,-70.99

In [28]:
# Detect potential outliers using IQR
for col in [
    "log_price",
    "accommodates",
    "bathrooms",
    "bedrooms",
    "beds",
    "number_of_reviews",
    "review_scores_rating"
]:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    count = (
        (df_clean[col] < lower) |
        (df_clean[col] > upper)
    ).sum()

    print(f"{col}: {count} potential outliers")

log_price: 1532 potential outliers
accommodates: 3604 potential outliers
bathrooms: 15812 potential outliers
bedrooms: 24236 potential outliers
beds: 5686 potential outliers
number_of_reviews: 8203 potential outliers
review_scores_rating: 1719 potential outliers

In [29]:
# Inspect the highest values in selected columns
for col in [
    "log_price",
    "accommodates",
    "bathrooms",
    "bedrooms",
    "beds",
    "number_of_reviews",
    "review_scores_rating"
]:
    print(f"\n--- {col} ---")
    print(df_clean[col].dropna().sort_values(ascending=False).head(10).to_list())

--- log_price ---
[7.6004023345004, 7.6004023345004, 7.6004023345004, 7.6004023345004, 7.6004023345004, 7.598399329323964, 7.598399329323964, 7.598399329323964, 7.598399329323964, 7.598399329323964]

--- accommodates ---
[16, 16, 16, 16, 16, 16, 16, 16, 16, 16]

--- bathrooms ---
[8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0, 8.0]

--- bedrooms ---
[10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]

--- beds ---
[18.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0, 16.0]

--- number_of_reviews ---
[605, 542, 532, 530, 525, 505, 495, 492, 480, 474]

--- review_scores_rating ---
[100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]

In [30]:
# Check values that violate basic logical expectations
print("Price below zero:", (df_clean["log_price"] < 0).sum())
print("Zero accommodates:", (df_clean["accommodates"] <= 0).sum())
print("Negative bathrooms:", (df_clean["bathrooms"] < 0).sum())
print("Negative bedrooms:", (df_clean["bedrooms"] < 0).sum())
print("Negative beds:", (df_clean["beds"] < 0).sum())
print("Negative reviews:", (df_clean["number_of_reviews"] < 0).sum())
print("Ratings outside 0–100:", (
    (df_clean["review_scores_rating"] < 0) |
    (df_clean["review_scores_rating"] > 100)
).sum())

Price below zero: 0
Zero accommodates: 0
Negative bathrooms: 0
Negative bedrooms: 0
Negative beds: 0
Negative reviews: 0
Ratings outside 0–100: 0

In [31]:
# Display column names grouped by data type
print("Numerical columns:")
print(df_clean.select_dtypes(include=["int64", "float64"]).columns.tolist())

print("\nCategorical/text columns:")
print(df_clean.select_dtypes(include=["object"]).columns.tolist())

print("\nBoolean columns:")
print(df_clean.select_dtypes(include=["bool"]).columns.tolist())

print("\nDate columns:")
print(df_clean.select_dtypes(include=["datetime"]).columns.tolist())

Numerical columns:
['id', 'log_price', 'accommodates', 'bathrooms', 'latitude', 'longitude', 'number_of_reviews', 'review_scores_rating', 'bedrooms', 'beds']

Categorical/text columns:
['property_type', 'room_type', 'amenities', 'bed_type', 'cancellation_policy', 'city', 'description', 'host_has_profile_pic', 'host_identity_verified', 'host_response_rate', 'name', 'neighbourhood', 'thumbnail_url', 'zipcode']

Boolean columns:
['cleaning_fee', 'instant_bookable']

Date columns:
['first_review', 'host_since', 'last_review']

In [32]:
# Create a separate copy for preprocessing
df_preprocessed = df_clean.copy()

# Remove the listing ID from potential model features
df_preprocessed = df_preprocessed.drop(columns=["id"])

print("Cleaned dataset shape:", df_clean.shape)
print("Preprocessing dataset shape:", df_preprocessed.shape)

Cleaned dataset shape: (74111, 29)
Preprocessing dataset shape: (74111, 28)

In [33]:
# Create useful features from dates
df_preprocessed["host_since_year"] = (
    df_preprocessed["host_since"].dt.year
)

df_preprocessed["first_review_year"] = (
    df_preprocessed["first_review"].dt.year
)

df_preprocessed["last_review_year"] = (
    df_preprocessed["last_review"].dt.year
)

# Count amenities listed for each property
def count_amenities(value):
    if pd.isna(value) or value == "Unknown" or value.strip() == "":
        return 0
    return len(value.strip("{}").split(","))

df_preprocessed["amenities_count"] = (
    df_preprocessed["amenities"].apply(count_amenities)
)

# Check the new features
print(df_preprocessed[
    [
        "host_since_year",
        "first_review_year",
        "last_review_year",
        "amenities_count"
    ].head()
])

print("\nNew dataset shape:", df_preprocessed.shape)

AttributeError: 'list' object has no attribute 'head'

In [34]:
# Display the first 5 rows of the new features
print(df_preprocessed[
    [
        "host_since_year",
        "first_review_year",
        "last_review_year",
        "amenities_count"
    ]
].head())

print("\nNew dataset shape:", df_preprocessed.shape)

   host_since_year  first_review_year  last_review_year  amenities_count
0           2012.0             2016.0            2016.0                9
1           2017.0             2017.0            2017.0               15
2           2016.0             2017.0            2017.0               19
3           2015.0                NaN               NaN               15
4           2015.0             2015.0            2017.0               12

New dataset shape: (74111, 32)

In [35]:
print(df_preprocessed["host_response_rate"].value_counts().head(15))

host_response_rate
100%       43254
Unknown    18299
90%         2277
80%         1113
0%           883
50%          611
70%          508
99%          448
67%          433
98%          425
94%          401
97%          400
96%          350
60%          337
95%          322
Name: count, dtype: int64

In [37]:
import numpy as np

In [38]:
# Convert percentage text into numeric proportions
df_preprocessed["host_response_rate"] = (
    df_preprocessed["host_response_rate"]
    .replace("Unknown", np.nan)
    .str.rstrip("%")
    .astype(float) / 100
)

# Check the conversion
print(df_preprocessed["host_response_rate"].head(10))
print("\nMissing response rates:",
      df_preprocessed["host_response_rate"].isnull().sum())

0    NaN
1    1.0
2    1.0
3    NaN
4    1.0
5    1.0
6    1.0
7    1.0
8    1.0
9    1.0
Name: host_response_rate, dtype: float64

Missing response rates: 18299

In [39]:
# Check missing values in the preprocessing dataset
missing_counts = df_preprocessed.isnull().sum()
print(missing_counts[missing_counts > 0].sort_values(ascending=False))

host_response_rate      18299
review_scores_rating    16722
first_review_year       15864
first_review            15864
last_review_year        15827
last_review             15827
host_since                188
host_since_year           188
dtype: int64

In [40]:
# Record which values were missing before filling them
df_preprocessed["response_rate_missing"] = (
    df_preprocessed["host_response_rate"].isna().astype(int)
)

df_preprocessed["rating_missing"] = (
    df_preprocessed["review_scores_rating"].isna().astype(int)
)

df_preprocessed["first_review_missing"] = (
    df_preprocessed["first_review"].isna().astype(int)
)

df_preprocessed["last_review_missing"] = (
    df_preprocessed["last_review"].isna().astype(int)
)

df_preprocessed["host_since_missing"] = (
    df_preprocessed["host_since"].isna().astype(int)
)

# Fill missing numeric values with their medians
numeric_fill_cols = [
    "host_response_rate",
    "review_scores_rating",
    "host_since_year",
    "first_review_year",
    "last_review_year"
]

for col in numeric_fill_cols:
    df_preprocessed[col] = df_preprocessed[col].fillna(
        df_preprocessed[col].median()
    )

# Verify the selected columns
print(df_preprocessed[numeric_fill_cols].isnull().sum())
print("\nNew dataset shape:", df_preprocessed.shape)

host_response_rate      0
review_scores_rating    0
host_since_year         0
first_review_year       0
last_review_year        0
dtype: int64

New dataset shape: (74111, 37)

### Categorical Encoding

One-hot encoding was selected for categorical features such as property type, room type, bed type, cancellation policy, and city. This creates separate binary columns for their categories without assigning artificial numerical rankings. Free-text fields and high-cardinality fields, such as listing names, descriptions, amenities, and URLs, were excluded from this basic encoding step because they require specialized processing.

In [41]:
import pandas as pd

# Create a separate copy for encoding
df_encoded = df_preprocessed.copy()

# Select categorical columns suitable for one-hot encoding
categorical_cols = [
    "property_type",
    "room_type",
    "bed_type",
    "cancellation_policy",
    "city",
    "host_has_profile_pic",
    "host_identity_verified"
]

# Convert selected categorical columns into binary columns
df_encoded = pd.get_dummies(
    df_encoded,
    columns=categorical_cols,
    dtype=int
)

print("Encoded dataset shape:", df_encoded.shape)
print(df_encoded.head())

Encoded dataset shape: (74111, 90)
   log_price                                          amenities  accommodates  \
0   5.010635  {"Wireless Internet","Air conditioning",Kitche...             3
1   5.129899  {"Wireless Internet","Air conditioning",Kitche...             7
2   4.976734  {TV,"Cable TV","Wireless Internet","Air condit...             5
3   6.620073  {TV,"Cable TV",Internet,"Wireless Internet",Ki...             4
4   4.744932  {TV,Internet,"Wireless Internet","Air conditio...             2

   bathrooms  cleaning_fee                                        description  \
0        1.0          True  Beautiful, sunlit brownstone 1-bedroom in the ...
1        1.0          True  Enjoy travelling during your stay in Manhattan...
2        1.0          True  The Oasis comes complete with a full backyard ...
3        1.0          True  This light-filled home-away-from-home is super...
4        1.0          True  Cool, cozy, and comfortable studio located in ...

  first_review  host_response_rate host_since  instant_bookable  ... city_DC  \
0   2016-06-18                 1.0 2012-03-26             False  ...       0
1   2017-08-05                 1.0 2017-06-19              True  ...       0
2   2017-04-30                 1.0 2016-10-25              True  ...       0
3          NaT                 1.0 2015-04-19             False  ...       0
4   2015-05-12                 1.0 2015-03-01              True  ...       1

   city_LA  city_NYC city_SF host_has_profile_pic_False  \
0        0         1       0                          0
1        0         1       0                          0
2        0         1       0                          0
3        0         0       1                          0
4        0         0       0                          0

   host_has_profile_pic_True  host_has_profile_pic_Unknown  \
0                          1                             0
1                          1                             0
2                          1                             0
3                          1                             0
4                          1                             0

  host_identity_verified_False host_identity_verified_True  \
0                            0                           1
1                            1                           0
2                            0                           1
3                            0                           1
4                            0                           1

   host_identity_verified_Unknown
0                               0
1                               0
2                               0
3                               0
4                               0

[5 rows x 90 columns]

In [42]:
from sklearn.preprocessing import StandardScaler

# Create another copy for scaling
df_scaled = df_encoded.copy()

# Select continuous numeric features to scale
scale_cols = [
    "log_price",
    "accommodates",
    "bathrooms",
    "bedrooms",
    "beds",
    "number_of_reviews",
    "review_scores_rating",
    "latitude",
    "longitude",
    "host_response_rate",
    "host_since_year",
    "first_review_year",
    "last_review_year",
    "amenities_count"
]

# Scale only the selected numeric columns
scaler = StandardScaler()
df_scaled[scale_cols] = scaler.fit_transform(df_scaled[scale_cols])

print("Scaled dataset shape:", df_scaled.shape)
print(df_scaled[scale_cols].describe().round(2))

Scaled dataset shape: (74111, 90)
       log_price  accommodates  bathrooms  bedrooms      beds  \
count   74111.00      74111.00   74111.00  74111.00  74111.00
mean       -0.00         -0.00       0.00      0.00     -0.00
std         1.00          1.00       1.00      1.00      1.00
min        -6.67         -1.00      -2.12     -1.49     -1.36
25%        -0.65         -0.54      -0.40     -0.31     -0.57
50%        -0.10         -0.54      -0.40     -0.31     -0.57
75%         0.61          0.39      -0.40     -0.31      0.23
max         3.93          5.96      11.64     10.26     13.00

       number_of_reviews  review_scores_rating  latitude  longitude  \
count           74111.00              74111.00  74111.00   74111.00
mean               -0.00                  0.00      0.00       0.00
std                 1.00                  1.00      1.00       1.00
min                -0.55                -10.73     -1.66      -1.39
25%                -0.53                 -0.22     -1.40      -1.20
50%                -0.39                  0.22      0.72       0.71
75%                 0.06                  0.65      0.75       0.85
max                15.44                  0.79      1.28       0.99

       host_response_rate  host_since_year  first_review_year  \
count            74111.00         74111.00           74111.00
mean                 0.00            -0.00              -0.00
std                  1.00             1.00               1.00
min                 -6.65            -3.30              -6.11
25%                  0.30            -0.57              -0.51
50%                  0.30            -0.03               0.29
75%                  0.30             0.52               0.29
max                  0.30             1.61               1.09

       last_review_year  amenities_count
count          74111.00         74111.00
mean              -0.00            -0.00
std                1.00             1.00
min              -13.24            -2.39
25%                0.42            -0.66
50%                0.42            -0.09
75%                0.42             0.63
max                0.42             9.86

### Numerical Scaling

Standardization was applied to selected numerical features using `StandardScaler`. The transformation places the features on comparable scales, with values centered around zero and scaled to approximately unit standard deviation. Binary indicators and one-hot encoded columns were not scaled. For future predictive modeling, the scaler must be fitted only on the training data and then applied to validation and test data to prevent data leakage.

In [43]:
# Check skewness of selected numeric features
skew_cols = [
    "log_price",
    "accommodates",
    "number_of_reviews",
    "beds",
    "amenities_count"
]

print(df_preprocessed[skew_cols].skew().round(2))

log_price            0.51
accommodates         2.23
number_of_reviews    3.70
beds                 3.36
amenities_count      0.79
dtype: float64

In [44]:
# Create a log-transformed review-count feature
df_preprocessed["number_of_reviews_log"] = np.log1p(
    df_preprocessed["number_of_reviews"]
)

# Compare the original and transformed distributions
print("Original skewness:",
      round(df_preprocessed["number_of_reviews"].skew(), 2))

print("Transformed skewness:",
      round(df_preprocessed["number_of_reviews_log"].skew(), 2))

Original skewness: 3.7
Transformed skewness: 0.26

### Skewness and Data Transformation

Skewness was examined for selected numerical features. A logarithmic transformation using `log1p()` was applied to the number of reviews to reduce the effect of very large review counts. The original feature was retained for comparison. The `log_price` feature was not transformed again because it was already log-transformed in the original dataset. Transformations should be evaluated before their use in a predictive model.

In [45]:
# Final dataset checks
print("Original dataset:", df_raw.shape)
print("Cleaned dataset:", df_clean.shape)
print("Encoded dataset:", df_encoded.shape)
print("Scaled dataset:", df_scaled.shape)

print("\nDuplicate rows:", df_clean.duplicated().sum())
print("Missing values in cleaned data:", df_clean.isnull().sum().sum())
print("Missing values in scaled data:", df_scaled.isnull().sum().sum())

print("\nFinal validation complete!")

Original dataset: (74111, 29)
Cleaned dataset: (74111, 29)
Encoded dataset: (74111, 90)
Scaled dataset: (74111, 90)

Duplicate rows: 0
Missing values in cleaned data: 48601
Missing values in scaled data: 31879

Final validation complete!

## Conclusion

In this assignment, the Airbnb dataset containing 74,111 records and 29 columns was explored and cleaned. Missing values, duplicate records, inconsistent categories, data types, and potential outliers were examined. Selected missing values were handled using appropriate methods, and categorical features were encoded using one-hot encoding. Numerical features were standardized, and additional features were created from dates and amenities. A logarithmic transformation was also considered for review counts. These steps prepared the data for further analysis and potential machine-learning applications. For future predictive modeling, preprocessing parameters should be fitted on training data only to prevent data leakage.

# 1. Dataset Description

**Dataset Title:** Airbnb Data

**Source:** Kaggle (insert the original dataset URL).

**Objective:** The dataset contains information about Airbnb listings. The objective of this assignment is to inspect, clean and preprocess the data so it can be used reliably for further analysis or machine learning.

**Dataset Size:** To be filled in using the actual number of rows and columns printed by the code.

**Main Features:** To be filled in after inspecting the column names.

In [11]:

print("Missing values in each column:")
display(df.isnull().sum().to_frame("Missing Values"))

print("\nMissing value percentages:")
missing_percent = (df.isnull().mean() * 100).round(2)
display(missing_percent.to_frame("Missing Percentage"))

Missing values in each column:

                        Missing Values
id                                   0
log_price                            0
property_type                        0
room_type                            0
amenities                            0
accommodates                         0
bathrooms                          200
bed_type                             0
cancellation_policy                  0
cleaning_fee                         0
city                                 0
description                          0
first_review                     15864
host_has_profile_pic               188
host_identity_verified             188
host_response_rate               18299
host_since                         188
instant_bookable                     0
last_review                      15827
latitude                             0
longitude                            0
name                                 0
neighbourhood                     6872
number_of_reviews                    0
review_scores_rating             16722
thumbnail_url                     8216
zipcode                            966
bedrooms                            91
beds                               131

Missing value percentages:

                        Missing Percentage
id                                    0.00
log_price                             0.00
property_type                         0.00
room_type                             0.00
amenities                             0.00
accommodates                          0.00
bathrooms                             0.27
bed_type                              0.00
cancellation_policy                   0.00
cleaning_fee                          0.00
city                                  0.00
description                           0.00
first_review                         21.41
host_has_profile_pic                  0.25
host_identity_verified                0.25
host_response_rate                   24.69
host_since                            0.25
instant_bookable                      0.00
last_review                          21.36
latitude                              0.00
longitude                             0.00
name                                  0.00
neighbourhood                         9.27
number_of_reviews                     0.00
review_scores_rating                 22.56
thumbnail_url                        11.09
zipcode                               1.30
bedrooms                              0.12
beds                                  0.18

In [12]:

print("Total duplicate rows:", df.duplicated().sum())

Total duplicate rows: 0

In [13]:

display(df.describe().T)

,count,mean,std,min,25%,50%,75%,max
id,74111.0,1.126662e+07,6.081735e+06,344.000000,6.261964e+06,1.225415e+07,1.640226e+07,2.123090e+07
log_price,74111.0,4.782069e+00,7.173938e-01,0.000000,4.317488e+00,4.709530e+00,5.220356e+00,7.600402e+00
accommodates,74111.0,3.155146e+00,2.153589e+00,1.000000,2.000000e+00,2.000000e+00,4.000000e+00,1.600000e+01
bathrooms,73911.0,1.235263e+00,5.820441e-01,0.000000,1.000000e+00,1.000000e+00,1.000000e+00,8.000000e+00
latitude,74111.0,3.844596e+01,3.080167e+00,33.338905,3.412791e+01,4.066214e+01,4.074610e+01,4.239044e+01
longitude,74111.0,-9.239753e+01,2.170532e+01,-122.511500,-1.183424e+02,-7.699696e+01,-7.395466e+01,-7.098505e+01
number_of_reviews,74111.0,2.090057e+01,3.782864e+01,0.000000,1.000000e+00,6.000000e+00,2.300000e+01,6.050000e+02
review_scores_rating,57389.0,9.406736e+01,7.836556e+00,20.000000,9.200000e+01,9.600000e+01,1.000000e+02,1.000000e+02
bedrooms,74020.0,1.265793e+00,8.521435e-01,0.000000,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+01
beds,73980.0,1.710868e+00,1.254142e+00,0.000000,1.000000e+00,1.000000e+00,2.000000e+00,1.800000e+01